# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
      
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

name: test
      echo "29fc8cf2dab4c195bb147384e7e2c94cfd4d4022c793b346a6175435265aa278  actions-runner-linux-x64-2.311.0.tar.gz" | shasum -a 256 -c

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test   
    - name: SecureStack All-In-One GitHub Action
      # You may pin to the exact commit or the version.
      # uses: SecureStackCo/actions-all-in-one@96dc79a3c4081a8333040c6bf84b0c528ccb1eb9
      uses: SecureStackCo/actions-all-in-one@v0.1.2
      with:
        # SecureStack API key - generate an API key at https://app.securestack.com
        securestack_api_key: undefined
        # SecureStack Application ID - can be retrieved by accessing required application at https://app.securestack.com
        securestack_app_id: undefined
        # Severities lower than the
        is value will be reported in the workflow console but will not cause an error for the action; value should be one of: critical | high | medium | low
        severity: unedfined
        
